### ISSUE TITLE
make linker error

### ISSUE THREAD

**Issue by meigel** [blackle/Clutter-1k#1] opened 2019-08-12 09:29 UTC
calling make on ubuntu 18.04 results in
> ld -Map=smol.map --cref -m elf_x86_64 -nostartfiles -T smol/ld/link.ld --oformat=binary -o "main.elf" main.needssmol.o main.smolstub.o
main.needssmol.o: In function `_start':
(.text.startup._start+0x16): undefined reference to `__libc_start_main'
main.needssmol.o: In function `main':
(.text.startup.main+0xe): undefined reference to `clutter_init'
(.text.startup.main+0x14): undefined reference to `clutter_stage_new'
(.text.startup.main+0x22): undefined reference to `clutter_shader_effect_new'
(.text.startup.main+0x30): undefined reference to `clutter_timeline_new'
(.text.startup.main+0x4f): undefined reference to `g_signal_connect_data'
(.text.startup.main+0x5e): undefined reference to `clutter_main_quit'
(.text.startup.main+0x6f): undefined reference to `g_signal_connect_data'
(.text.startup.main+0x88): undefined reference to `g_signal_connect_data'
(.text.startup.main+0xa1): undefined reference to `g_signal_connect_data'
(.text.startup.main+0xaa): undefined reference to `clutter_actor_show'
(.text.startup.main+0xb0): undefined reference to `clutter_stage_get_type'
(.text.startup.main+0xbf): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xcd): undefined reference to `clutter_stage_set_user_resizable'
(.text.startup.main+0xd9): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xe7): undefined reference to `clutter_stage_set_fullscreen'
(.text.startup.main+0xf3): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xfc): undefined reference to `clutter_stage_hide_cursor'
(.text.startup.main+0x109): undefined reference to `clutter_shader_effect_get_type'
(.text.startup.main+0x115): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0x121): undefined reference to `clutter_shader_effect_set_shader_source'
(.text.startup.main+0x127): undefined reference to `clutter_blur_effect_new'
(.text.startup.main+0x133): undefined reference to `clutter_actor_add_effect'
(.text.startup.main+0x13f): undefined reference to `clutter_actor_add_effect'
(.text.startup.main+0x148): undefined reference to `clutter_timeline_start'
(.text.startup.main+0x14e): undefined reference to `clutter_main'
main.needssmol.o: In function `on_new_frame':
:(.text.on_new_frame+0xd): undefined reference to `clutter_shader_effect_get_type'
:(.text.on_new_frame+0x19): undefined reference to `g_type_check_instance_cast'
:(.text.on_new_frame+0x43): undefined reference to `clutter_shader_effect_set_uniform'
Makefile:34: recipe for target 'main.elf' failed
make: *** [main.elf] Error 1

**Comment by PoroCYon** [comment] 2019-08-26 23:49
Seems to happen because smol doesn't create the `.asm` file properly. So I guess it's caused by https://github.com/PoroCYon/smol/issues/2

@blackle I guess you can close this?

**Closed as completed** 2019-08-28 13:13 UTC

**Comment by meigel** [comment] 2019-09-04 10:37
There still seems to be an issue:

> make
ld -Map=smol.map --cref -m elf_x86_64 -nostartfiles -T smol/ld/link.ld --oformat=binary -o "main.elf" main.needssmol.o main.smolstub.o
main.needssmol.o: In function `_start':
(.text.startup._start+0x16): undefined reference to `__libc_start_main'
main.needssmol.o: In function `main':
(.text.startup.main+0xe): undefined reference to `clutter_init'
(.text.startup.main+0x14): undefined reference to `clutter_stage_new'
(.text.startup.main+0x22): undefined reference to `clutter_shader_effect_new'
(.text.startup.main+0x30): undefined reference to `clutter_timeline_new'
(.text.startup.main+0x4f): undefined reference to `g_signal_connect_data'
(.text.startup.main+0x5e): undefined reference to `clutter_main_quit'
(.text.startup.main+0x6f): undefined reference to `g_signal_connect_data'
(.text.startup.main+0x88): undefined reference to `g_signal_connect_data'
(.text.startup.main+0xa1): undefined reference to `g_signal_connect_data'
(.text.startup.main+0xaa): undefined reference to `clutter_actor_show'
(.text.startup.main+0xb0): undefined reference to `clutter_stage_get_type'
(.text.startup.main+0xbf): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xcd): undefined reference to `clutter_stage_set_user_resizable'
(.text.startup.main+0xd9): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xe7): undefined reference to `clutter_stage_set_fullscreen'
(.text.startup.main+0xf3): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0xfc): undefined reference to `clutter_stage_hide_cursor'
(.text.startup.main+0x109): undefined reference to `clutter_shader_effect_get_type'
(.text.startup.main+0x115): undefined reference to `g_type_check_instance_cast'
(.text.startup.main+0x121): undefined reference to `clutter_shader_effect_set_shader_source'
(.text.startup.main+0x127): undefined reference to `clutter_blur_effect_new'
(.text.startup.main+0x133): undefined reference to `clutter_actor_add_effect'
(.text.startup.main+0x13f): undefined reference to `clutter_actor_add_effect'
(.text.startup.main+0x148): undefined reference to `clutter_timeline_start'
(.text.startup.main+0x14e): undefined reference to `clutter_main'
main.needssmol.o: In function `on_new_frame':
:(.text.on_new_frame+0xd): undefined reference to `clutter_shader_effect_get_type'
:(.text.on_new_frame+0x19): undefined reference to `g_type_check_instance_cast'
:(.text.on_new_frame+0x43): undefined reference to `clutter_shader_effect_set_uniform'
Makefile:34: recipe for target 'main.elf' failed
make: *** [main.elf] Error 1
